#!/bin/bash

#NFS Servers ip
NFS=true
NFSSRV='192.168.1.14'

juju-log "Installing ompss working node"
set -eu # -x for verbose logging to juju debug-log

if $NFS; then
   juju-log "mounting binary dir"
   sudo apt-get -y install nfs-common
   if [ -d "/srv/ompss" ]; then
      sudo umount /srv/ompss
      sudo rm -Rf /srv/ompss
   fi
   sudo mkdir /srv/ompss
   sudo chmod 777 /srv/ompss
   sudo mount $NFSSRV:/srv/nfs4/ompss /srv/ompss

   echo "$NFSSRV:/srv/nfs4/ompss /srv/ompss nfs auto 0 0" >> /etc/fstab
fi


juju-log "apt-get install git"
sudo apt-get -y install git


juju-log "Cloning repository"
if [ -d "/usr/local/OMPSS.git" ]; then
   sudo rm -Rf /usr/local/OMPSS.git
fi
sudo git clone https://github.com/nereliz/OMPSS-Server.git /usr/local/OMPSS.git

juju-log "Creating symilinks"
if [ ! -L "/etc/ompss" ]; then
   sudo ln -s /usr/local/OMPSS.git/ompss /etc/ompss
fi

if $NFS; then
   if [ -f /srv/ompss/config.ini ]; then
      sudo rm /etc/ompss/config.ini
      sudo ln -s /srv/ompss/config.ini /etc/ompss/config.ini   
   fi
fi


if [ ! -L "/etc/init.d/ompss" ]; then
   sudo ln -s /etc/ompss/init.d/ompss /etc/init.d/ompss
fi

juju-log "Enabling 4645 and 3306 ports"
#sudo ufw enable
#sudo allow 4645
open-port 4645
open-port 3306

juju-log "Installing Qt4 libraries"
sudo apt-get -y install libqt4-*

juju-log "Installing mysql-client"
sudo apt-get -y install mysql-client

juju-log "Installing make"
sudo apt-get -y install make

juju-log "Installing c++ compiler"
sudo apt-get -y install g++

juju-log "Installing java runtime"
sudo apt-get -y install openjdk-6-jre
sudo apt-get -y install openjdk-6-jdk

juju-log "Installing fortran compiler"
sudo apt-get -y install gfortran
